camunda:
  client:
    mode: self-managed
    grpc-address: http://localhost:26500
    rest-address: http://localhost:8080
    auth:
      username: demo
      password: demo

logging:
  level:
    io.camunda.client.impl.CamundaCallCredentials: ERROR
    io.camunda.connector.runtime.inbound: ERROR
