camunda:
  connector:
    agenticai:
      mcp:
        client:
          enabled: true
          clients:
            time:
              stdio:
                command: docker
                args:
                  - 'run'
                  - '-i'
                  - '--rm'
                  - 'mcp/time'
