camunda:
  client:
    mode: self-managed
    grpc-address: http://localhost:26500
    rest-address: http://localhost:8080
    auth:
      username: demo
      password: demo
  connector:
    agenticai:
      aiagent:
        enabled: true
      ad-hoc-tools-schema-resolver:
        enabled: false
      mcp:
        remote-client:
          enabled: false

logging:
  level:
    io.camunda.client.impl.CamundaCallCredentials: ERROR
    io.camunda.connector.runtime.inbound: ERROR
