server:
  port: 8181
spring:
  application:
    name: agentic-ai-customizations
  jpa:
    hibernate:
      ddl-auto: validate

camunda:
  connector:
    agenticai:
      ad-hoc-tools-schema-resolver:
        enabled: false
      mcp:
        remote-client:
          enabled: false
      a2a:
        client:
          outbound:
            enabled: false
          polling:
            enabled: false
          webhook:
            enabled: false
